name: Publish GitHub Pages

env:
  PYTHON_VERSION: 3.13

on:
  push:
    branches:
      - feature/add_deploy_to_pages

jobs:
  build:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build project
        run: |
          python -m pygbag --build minimal_sample

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: minimal_sample/build/web

  deploy:
    needs: build
    runs-on:
      - ubuntu-latest
    
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
